// Generated by scripts/svg2drawlist.py — do not edit by hand.
// Requires imgui.h and the helpers from svg_runtime.h.
#ifndef SVG_ICONS_IMGUI_H
#define SVG_ICONS_IMGUI_H

#include <imgui.h>
#include <math.h>   // fmodf (dash windows)
#include "svg_runtime.h"

// Generated by scripts/svg2drawlist.py from dots-loading.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_dots_loading(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    static const float s0_op_k[] = {0.25f, 1.0f, 0.25f};
    dl->AddCircleFilled(SVG_P(6.0f, 12.0f), (2.2f) * (1.0f * ks), (tint & ~IM_COL32_A_MASK) | ((ImU32)(int)(255.0f * ((SvgKeysLoop(t, 0.0, 1.2, s0_op_k, 3, NULL, NULL)))) << IM_COL32_A_SHIFT));
    static const float s1_op_k[] = {0.25f, 1.0f, 0.25f};
    dl->AddCircleFilled(SVG_P(12.0f, 12.0f), (2.2f) * (1.0f * ks), (tint & ~IM_COL32_A_MASK) | ((ImU32)(int)(255.0f * ((SvgKeysLoop(t, 0.2, 1.2, s1_op_k, 3, NULL, NULL)))) << IM_COL32_A_SHIFT));
    static const float s2_op_k[] = {0.25f, 1.0f, 0.25f};
    dl->AddCircleFilled(SVG_P(18.0f, 12.0f), (2.2f) * (1.0f * ks), (tint & ~IM_COL32_A_MASK) | ((ImU32)(int)(255.0f * ((SvgKeysLoop(t, 0.4, 1.2, s2_op_k, 3, NULL, NULL)))) << IM_COL32_A_SHIFT));
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-check.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_check(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->PathClear();
    dl->PathLineTo(SVG_P(4.0f, 13.0f));
    dl->PathLineTo(SVG_P(9.0f, 18.0f));
    dl->PathLineTo(SVG_P(20.0f, 6.0f));
    dl->PathStroke(tint, 2.5f * ks, 0);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-chevron-down.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_chevron_down(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->PathClear();
    dl->PathLineTo(SVG_P(5.0f, 9.0f));
    dl->PathLineTo(SVG_P(12.0f, 16.0f));
    dl->PathLineTo(SVG_P(19.0f, 9.0f));
    dl->PathStroke(tint, 2.5f * ks, 0);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-close.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_close(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->PathClear();
    dl->PathLineTo(SVG_P(5.0f, 5.0f));
    dl->PathLineTo(SVG_P(19.0f, 19.0f));
    dl->PathLineTo(SVG_P(19.0f, 5.0f));
    dl->PathLineTo(SVG_P(5.0f, 19.0f));
    dl->PathStroke(tint, 2.5f * ks, 0);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-folder.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_folder(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->PathClear();
    dl->PathLineTo(SVG_P(3.0f, 6.0f));
    dl->PathLineTo(SVG_P(9.0f, 6.0f));
    dl->PathLineTo(SVG_P(11.0f, 8.5f));
    dl->PathLineTo(SVG_P(21.0f, 8.5f));
    dl->PathLineTo(SVG_P(21.0f, 19.0f));
    dl->PathLineTo(SVG_P(3.0f, 19.0f));
    dl->PathStroke(tint, 2.0f * ks, ImDrawFlags_Closed);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-gear.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_gear(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->AddCircle(SVG_P(12.0f, 12.0f), (4.0f) * (1.0f * ks), tint, 0, 2.0f * ks);
    dl->AddLine(SVG_P(18.2f, 12.0f), SVG_P(21.4f, 12.0f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(16.38f, 16.38f), SVG_P(18.65f, 18.65f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(12.0f, 18.2f), SVG_P(12.0f, 21.4f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(7.62f, 16.38f), SVG_P(5.35f, 18.65f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(5.8f, 12.0f), SVG_P(2.6f, 12.0f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(7.62f, 7.62f), SVG_P(5.35f, 5.35f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(12.0f, 5.8f), SVG_P(12.0f, 2.6f), tint, 2.2f * ks);
    dl->AddLine(SVG_P(16.38f, 7.62f), SVG_P(18.65f, 5.35f), tint, 2.2f * ks);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-pause.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_pause(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->AddRectFilled(SVG_P(5.0f, 4.0f), SVG_P((5.0f) + (4.5f), (4.0f) + (16.0f)), tint, 0.0f * ks);
    dl->AddRectFilled(SVG_P(14.5f, 4.0f), SVG_P((14.5f) + (4.5f), (4.0f) + (16.0f)), tint, 0.0f * ks);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-play.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_play(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    {
        static const ImVec2 kp[] = {ImVec2(6.0f, 4.0f), ImVec2(20.0f, 12.0f), ImVec2(6.0f, 20.0f)};
        dl->PathClear();
        for (int i = 0; i < IM_COUNTOF(kp); i++) dl->PathLineTo(SVG_P(kp[i].x, kp[i].y));
        dl->PathFillConcave(tint);
    }
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from icon-search.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_icon_search(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->AddCircle(SVG_P(10.5f, 10.5f), (6.5f) * (1.0f * ks), tint, 0, 2.0f * ks);
    dl->AddLine(SVG_P(15.5f, 15.5f), SVG_P(20.5f, 20.5f), tint, 2.5f * ks);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from progress-fill.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_progress_fill(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    dl->AddRectFilled(SVG_P(1.0f, 10.0f), SVG_P((1.0f) + (22.0f), (10.0f) + (4.0f)), (tint & ~IM_COL32_A_MASK) | ((ImU32)(int)(255.0f * (0.25f)) << IM_COL32_A_SHIFT), 2.0f * ks);
    static const float s1_w_k[] = {2.0f, 22.0f, 2.0f};
    dl->AddRectFilled(SVG_P(1.0f, 10.0f), SVG_P((1.0f) + (SvgKeysLoop(t, 0.0, 2.5, s1_w_k, 3, NULL, NULL)), (10.0f) + (4.0f)), tint, 2.0f * ks);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from pulse-dot.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_pulse_dot(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    static const float s0_op_k[] = {1.0f, 0.4f, 1.0f};
    static const float s0_r_k[] = {4.0f, 6.0f, 4.0f};
    dl->AddCircleFilled(SVG_P(12.0f, 12.0f), (SvgKeysLoop(t, 0.0, 1.6, s0_r_k, 3, NULL, NULL)) * (1.0f * ks), (tint & ~IM_COL32_A_MASK) | ((ImU32)(int)(255.0f * ((SvgKeysLoop(t, 0.0, 1.6, s0_op_k, 3, NULL, NULL)))) << IM_COL32_A_SHIFT));
    static const float s1_op_k[] = {0.8f, 0.0f};
    static const float s1_r_k[] = {5.0f, 10.0f};
    dl->AddCircle(SVG_P(12.0f, 12.0f), (SvgKeysLoop(t, 0.0, 1.6, s1_r_k, 2, NULL, NULL)) * (1.0f * ks), (tint & ~IM_COL32_A_MASK) | ((ImU32)(int)(255.0f * ((SvgKeysLoop(t, 0.0, 1.6, s1_op_k, 2, NULL, NULL)))) << IM_COL32_A_SHIFT), 0, 1.5f * ks);
#undef SVG_P
}

// Generated by scripts/svg2drawlist.py from spinner-arc.svg — do not edit by hand.
// Maps viewBox (0,0,24,24) into [origin, origin+size].
// t = seconds (ImGui::GetTime()); tint replaces --tint color if given.
inline void DrawSvg_spinner_arc(ImDrawList* dl, const ImVec2& origin, const ImVec2& size, float t,
                       ImU32 tint = IM_COL32(255, 255, 255, 255))
{
    (void)t; (void)tint;
    const float kx = size.x / 24.0f, ky = size.y / 24.0f, ks = (kx + ky) * 0.5f;
    (void)kx; (void)ky; (void)ks;
#define SVG_P(x_, y_) ImVec2(origin.x + float(x_) * kx, origin.y + float(y_) * ky)
    static const float s0_rot_k[] = {0.0f, 360.0f};
    {
        static const ImVec2 kp[] = {ImVec2(21.0f, 12.0f), ImVec2(20.923f, 13.1747f), ImVec2(20.6933f, 14.3294f), ImVec2(20.3149f, 15.4442f), ImVec2(19.7942f, 16.5f), ImVec2(19.1402f, 17.4789f), ImVec2(18.364f, 18.364f), ImVec2(17.4789f, 19.1402f), ImVec2(16.5f, 19.7942f), ImVec2(15.4442f, 20.3149f), ImVec2(14.3294f, 20.6933f), ImVec2(13.1747f, 20.923f), ImVec2(12.0f, 21.0f), ImVec2(10.8253f, 20.923f), ImVec2(9.67063f, 20.6933f), ImVec2(8.55585f, 20.3149f), ImVec2(7.5f, 19.7942f), ImVec2(6.52115f, 19.1402f), ImVec2(5.63604f, 18.364f), ImVec2(4.85982f, 17.4789f), ImVec2(4.20577f, 16.5f), ImVec2(3.68508f, 15.4442f), ImVec2(3.30667f, 14.3294f), ImVec2(3.077f, 13.1747f), ImVec2(3.0f, 12.0f), ImVec2(3.077f, 10.8253f), ImVec2(3.30667f, 9.67063f), ImVec2(3.68508f, 8.55585f), ImVec2(4.20577f, 7.5f), ImVec2(4.85982f, 6.52115f), ImVec2(5.63604f, 5.63604f), ImVec2(6.52115f, 4.85982f), ImVec2(7.5f, 4.20577f), ImVec2(8.55585f, 3.68508f), ImVec2(9.67063f, 3.30667f), ImVec2(10.8253f, 3.077f), ImVec2(12.0f, 3.0f), ImVec2(13.1747f, 3.077f), ImVec2(14.3294f, 3.30667f), ImVec2(15.4442f, 3.68508f), ImVec2(16.5f, 4.20577f), ImVec2(17.4789f, 4.85982f), ImVec2(18.364f, 5.63604f), ImVec2(19.1402f, 6.52115f), ImVec2(19.7942f, 7.5f), ImVec2(20.3149f, 8.55585f), ImVec2(20.6933f, 9.67063f), ImVec2(20.923f, 10.8253f), ImVec2(21.0f, 12.0f)};
        ImVec2 rp[IM_COUNTOF(kp)];
        SvgRotatePts(rp, kp, IM_COUNTOF(kp), 12.0f, 12.0f, SvgKeysLoop(t, 0.0, 1.0, s0_rot_k, 2, NULL, NULL));
        dl->PathClear();
        static const float cl[] = {0.0f, 1.17726f, 2.35451f, 3.53177f, 4.70903f, 5.88628f, 7.06354f, 8.24079f, 9.41805f, 10.5953f, 11.7726f, 12.9498f, 14.1271f, 15.3043f, 16.4816f, 17.6588f, 18.8361f, 20.0134f, 21.1906f, 22.3679f, 23.5451f, 24.7224f, 25.8996f, 27.0769f, 28.2542f, 29.4314f, 30.6087f, 31.7859f, 32.9632f, 34.1404f, 35.3177f, 36.4949f, 37.6722f, 38.8495f, 40.0267f, 41.204f, 42.3812f, 43.5585f, 44.7357f, 45.913f, 47.0903f, 48.2675f, 49.4448f, 50.622f, 51.7993f, 52.9765f, 54.1538f, 55.331f, 56.5083f};
        for (int i = 0; i < IM_COUNTOF(kp); i++)
            if (cl[i] >= 0.0f && cl[i] <= 42.0f) dl->PathLineTo(SVG_P(rp[i].x, rp[i].y));
        dl->PathStroke(tint, 2.5f * ks, 0);
    }
#undef SVG_P
}

#endif // guard
